package DoctorAdminBackend.AdminBackend.Model;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.UUID;

import org.hibernate.annotations.GenericGenerator;

import com.fasterxml.jackson.annotation.JsonFormat; // For formatting LocalDateTime
import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

import lombok.Data;

@Data
@Entity
@Table(name = "appointments")
public class Appointment {

    @Id
    @GeneratedValue(generator = "uuid2")
    @GenericGenerator(name = "uuid2", strategy = "uuid2")
    private UUID id;

    @ManyToOne
    @JoinColumn(name = "patient_id", referencedColumnName = "id") // Maps to the "id" column in the "patients" table
  //  @JsonIgnore 
    private PatientModel patient;

    @ManyToOne
    @JoinColumn(name = "doctor_id", referencedColumnName = "id") // Maps to the "id" column in the "doctors" table
   // @JsonIgnore 
    private Doctor doctor;

    @Column(name = "AppointmentStartTime")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime appointmentDate;

    @Column(name = "AppointmentEndTime")
  //  @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime appointmentEndTime;

    public String getFormattedAppointmentDate() {
        if (appointmentDate == null || appointmentEndTime == null) {
            return null; // Return null or handle accordingly if either date is missing
        }

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("d MMM yyyy, hh:mm a");
        return appointmentDate.format(formatter) + " - " + appointmentEndTime.format(formatter);
    }

    // Getters and setters are generated by Lombok's @Data annotation

    public PatientModel getPatient() {
        return patient;
    }

    public void setPatient(PatientModel patient) {
        this.patient = patient;
    }

    public Doctor getDoctor() {
        return doctor;
    }

    public void setDoctor(Doctor doctor) {
        this.doctor = doctor;
    }

    public LocalDateTime getAppointmentDate() {
        return appointmentDate;
    }
     
    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
    public void setAppointmentDate(LocalDateTime appointmentDate) {
        this.appointmentDate = appointmentDate;
    }
}
