# Data source configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/doctoradmin
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.datasource.driver-class-name=com.postgresql.cj.jdbc.Driver

# Enable Hibernate SQL logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.date-format=dd/MM/yyyy