# Data source configuration
spring.datasource.url=jdbc:postgresql://postgres.railway.internal/doctoradmin
spring.datasource.username=postgres
spring.datasource.password=gMuuzfiGEnembfapOnOBvwnNCGRZXZAf
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.datasource.driver-class-name=com.postgresql.cj.jdbc.Driver

# Enable Hibernate SQL logging
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.date-format=dd/MM/yyyy